/**
 * Represents a torus (doughnut shape) generated by revolving a circle.
 */
export default class Torus {
  private R: number; // Major radius (distance from center to tube center)
  private r: number; // Minor radius (tube radius)

  /**
   * @param R - Major radius (must be positive)
   * @param r - Minor radius (must be positive and less than R)
   */
  constructor(R: number, r: number) {
    if (R <= 0 || r <= 0) {
      throw new Error("Radii must be positive.");
    }
    if (r >= R) {
      throw new Error("Minor radius must be less than major radius.");
    }
    this.R = R;
    this.r = r;
  }

  /** Gets the major radius. */
  get majorRadius(): number {
    return this.R;
  }

  /** Gets the minor radius. */
  get minorRadius(): number {
    return this.r;
  }

  /** Calculates the surface area: A = 4π²Rr */
  get surfaceArea(): number {
    return 4 * Math.PI ** 2 * this.R * this.r;
  }

  /** Calculates the volume: V = 2π²Rr² */
  get volume(): number {
    return 2 * Math.PI ** 2 * this.R * this.r ** 2;
  }
}
