name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 24

    - run: npm install

    - run: npm run docs 

    - name: Configure git for gh-pages
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - run: gh-pages -d docs -r https://x-access-token:${GH_TOKEN}@github.com/kevindmorris/matician.git
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
