name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 24

    - name: Install dependencies
      run: npm install

    - name: Deploy to GitHub Pages
      run: npm run deploy

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
